-- Enum Types
CREATE TYPE user_role AS ENUM ('admin', 'dispatcher', 'driver', 'customer');
CREATE TYPE shipment_status AS ENUM (
  'CREATED', 'PICKED_UP', 'IN_TRANSIT', 'AT_HUB',
  'OUT_FOR_DELIVERY', 'DELIVERED', 'FAILED_ATTEMPT', 'RETURNED', 'CANCELLED'
);
CREATE TYPE service_type AS ENUM ('STANDARD', 'EXPRESS', 'SAME_DAY');
CREATE TYPE vehicle_status AS ENUM ('AVAILABLE', 'ON_TRIP', 'MAINTENANCE', 'RETIRED');
CREATE TYPE trip_status AS ENUM ('PLANNED', 'ONGOING', 'COMPLETED', 'CANCELLED');
CREATE TYPE invoice_status AS ENUM ('PENDING', 'PAID', 'CANCELLED');
CREATE TYPE hub_status AS ENUM ('ACTIVE', 'INACTIVE', 'MAINTENANCE');
CREATE TYPE customer_type AS ENUM ('INDIVIDUAL', 'BUSINESS');
CREATE TYPE employee_designation AS ENUM ('DISPATCHER', 'ADMIN', 'HUB_MANAGER');
